### ISSUE TITLE
Research Shiny modules

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyPsych#1]
I have heard that modules are the new way to build and create ShinyApps elegantly. Try some googling  ...

**Comment by mdsteiner** [comment]
After reading a bit about modules and watching their tutorial video, I think this will be great for what we plan to do. It allows you to write modules and then call them like a function. As far as I've understood things,  this will also make it very easy to write it as a package. So I think we can write modules for the different tasks and questionnaires and then let people build their app by just merging the different components they'd like to have. However this will probably not impact performance, but the RStudio guys are convinced, that the shiny server can handle big amount of traffic, you just need to program your apps in the right way (good code).

I'll try to come up with a module of something that we can discuss on monday if it works well and if so what modules we want to have.

**Comment by ndphillips** [comment]
Beautiful. Let's try to use this functionality as much as possible then! Can you add links to some examples / tutorials here for reference?

**Comment by mdsteiner** [comment]
### Tutorials from shiny webpage:
- [Written Tutorial][1]
- [Video Tutorial][2]

### Other written Tutorials and blogposts:
- [From Locke Data Webpage][3]
- [From Aridhia Webpage][4]

[1]:https://shiny.rstudio.com/articles/modules.html
[2]:https://www.rstudio.com/resources/webinars/understanding-shiny-modules/
[3]:https://itsalocke.com/shiny-module-design-patterns-pass-module-input-to-other-modules/
[4]:http://www.aridhia.com/blog/using-shiny-modules-to-simplify-building-complex-apps/

**Comment by mdsteiner** [comment]
The more I'm programming different parts (I'm currently still at the questionnaire and try to make it flexible enough so as to be able to call different input values but also text values, so this function would serve to create all the pages that are not a specific task) the more I get concerned if using modules is necessary. We probably don't need it because modules are just a way of creating separate namespaces but this is done in the UI part. Since we don't do this, it's probably equivalent to just calling functions. Of course there is a problem with the unique ids that needs to be solved, but given the flexibility we'd like to have I'm not sure how to do this with modules. I'll try to come up with a solution based on functions and show it to you on monday.
I didn't yet push code to github because each time I do this you'd have to merge it. So I guess I'll just upload what I have tomorrow evening.

**Comment by ndphillips** [comment]
Sure sounds good. For me the nicest thing about modules was that all the code was functionalized anyway. so if using standard functions makes more sense than a module, then certainly go for simple functions.
