### ISSUE TITLE
Add a password check

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/ShinyPsych#41]
if a passwordInput is used, give the possibility to check enter the reference password in the text file

**Comment by ndphillips** [comment]
Could implement a hashed version to 'hide' the true password

**Comment by ktrutmann** [comment]
Where is the package "digest" actually used? If possible I would propose replacing it with the "openssl" package, as it is made for secure hashing and supports the SHA-512 algorithm, which would be optimal for this purpose.

**Comment by mdsteiner** [comment]
If I remember correctly, the digest function is only used in `saveData()`, where it's used to generate unique filenames of the structure "ID+sys.Time()+digest+suffix". So I'm not sure whether we need to change this, but we could of course in order to have fewer dependencies.

**Comment by ktrutmann** [comment]
I think it makes sense to have as few as possible, especially if they do essentially the same. Il change it and keep an eye open for other instances where it is used.

**Comment by ktrutmann** [comment]
It turned out that openssl does not support "digesting" a data.frame (which is done in saveData()), and while digest does support the SHA-512 algorithm, their documentation mentions not using it for "cryptographic purposes" and referrs to the "more thoroughly tested" openssl package. Therefore I think it's best to just leave them both in, even though they do **almost** the same.
