### ISSUE TITLE
Issue with install on AWS

### ISSUE THREAD

**Issue by pbrews7933** [ndphillips/ShinyPsych#71]
Having an issue attempting to install on AWS with a Shiny AMI.   Any ideas?

> devtools::install_github("ndphillips/ShinyPsych", build_vignettes = TRUE)
Downloading GitHub repo ndphillips/ShinyPsych@master
from URL https://api.github.com/repos/ndphillips/ShinyPsych/zipball/master
Installing ShinyPsych
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  '/tmp/Rtmp5XxWV7/devtools59d3f1d3f39/mdsteiner-ShinyPsych-de44c5a' --no-resave-data --no-manual 

* checking for file ‘/tmp/Rtmp5XxWV7/devtools59d3f1d3f39/mdsteiner-ShinyPsych-de44c5a/DESCRIPTION’ ... OK
* preparing ‘ShinyPsych’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
pandoc: Could not fetch ../inst/pictures/screenshot_bandit.png
../inst/pictures/screenshot_bandit.png: openBinaryFile: does not exist (No such file or directory)
Error: processing vignette 'ShinyPsych_Bandit.Rmd' failed with diagnostics:
pandoc document conversion failed with error 67
Execution halted
Installation failed: Command failed (1)

**Comment by mdsteiner** [comment]
I can't replicate the error on my computer, but I noticed that we used .PNG instead of .png (I think there was once an issue with installing it on windows that made this necessary). We'll look into it ASAP to give you a more satisfying answer and fix it. Meanwhile, if you don't need the vignettes, you coul just set `build_vignettes = FALSE` which will hopefully omit the problem.


A side note: You're using `devtools::install_github("ndphillips/...)`, but we moved the repo some time ago, so you may want to use `devtools::install_github("mdsteiner/ShinyPsych", build_vignettes = TRUE)` (although "ndphillips/ShinyPsych" still seems to lead to the correct repository).

**Comment by pbrews7933** [comment]
I was able to install and run the app with build_vignettes = FALSE  and I can get the vignette from my personal laptop so I have a usable workaround.  Thanks, Paul
